### ISSUE TITLE
Create and Publish as a Package

### ISSUE THREAD

**Issue by EdBarrancos** [EdBarrancos/ObjectSystem.jl#46]

**Comment by EdBarrancos** [comment]
https://julialang.org/contribute/developing_package/

**Comment by EdBarrancos** [comment]
https://github.com/JuliaRegistries/General/pull/91540

**Comment by EdBarrancos** [comment]
Click on the "install" button above to add the registration bot to your repository
Set the [(Julia)Project.toml](https://github.com/JuliaComputing/Registrator.jl/blob/master/Project.toml) version field in your repository to your new desired version.
Comment @JuliaRegistrator register on the commit/branch you want to register (e.g. like https://github.com/JuliaRegistries/Registrator.jl/issues/61#issuecomment-483486641 or [here](https://github.com/chakravala/Grassmann.jl/commit/3c3a92610ebc8885619f561fe988b0d985852fce#commitcomment-33233149)).
If something is incorrect, adjust, and redo step 2.
If the automatic tests pass, but a moderator makes suggestions (e.g., manually updating your (Julia)Project.toml to include a [compat] section with version requirements for dependencies), then incorporate suggestions as you see fit into a new commit, and redo step 2 for the new commit. You don't need to do anything to close out the old request.

**Comment by EdBarrancos** [comment]
Lowercase package name juliaobjectsystem contains the string "julia".
Repo URL does not end with /name.jl.git, where name is the package name
There is no compat entry for julia.
The following dependencies do not have a [compat] entry that is upper-bounded and only includes a finite number of breaking releases: Suppressor
No licenses detected in the package's top-level folder. An OSI-approved license is required.

**Comment by EdBarrancos** [comment]
https://github.com/JuliaRegistries/General/pull/91575

**Comment by EdBarrancos** [comment]
https://github.com/JuliaRegistries/General/pull/91589

**Comment by PallHaraldsson** [comment]
@EdBarrancos I'm very intrigued about your package.

Seeing an open pending registration and this issue, I thought it had not gone through and you had a change to become package 10,000, but actually your package is merged so you could close all registration PRs and this issue.

Your package seems well documented; also this one:
https://github.com/Suzhou-Tongyuan/ObjectOriented.jl

Did you know about that one?

https://github.com/JuliaRegistries/General/pull/91589

**Comment by EdBarrancos** [comment]
Hey @PallHaraldsson 

I forgot to close this issue XD

I did not know about it previously, but after I finished I found about it. It is an interesting one, I think we take two different approaches to solve the same problem

**Comment by PallHaraldsson** [comment]
I know of Smalltalk, and its claim to first object-oriented (or first to use that term, actually Simula earlier). Ok to use that term it for this, ans Smalltalk-like? But since there are two Julia packages (and more relating to...), and regrettable that you didn't know of the other, in case to similar (or good to have both types?):

I propose you (or I) get it documented in JuliaLang's docs. So people may know of, and at least not reimplement either (or a 3rd option?).

I suggest something like "Julia is object-oriented, but based on composition, not inheritance of implementation, not implementing classes or multiple inheritance. Two systems add such features. The package ObjectOriented.jl implementing Python's way of object orientation, and ObjectSystem.jl supporting meta-classes, like Smalltalk, the first object-oriented language, or actually in a way more similar to as done for Common Lisp (i.e. with CLOS) and Dylan languages." And link to your docs. [You have at least on typo there.]

You mention Python, but I guess no need to mention, since you don't implement they're way fully. You mention an extension, would it then be?
